package com.ridelink.account.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * A RideLink account (passenger, driver or admin), stored in account_db.
 * The id is a UUID string generated by the service, so other services can
 * reference it as a stable identifier instead of a Mongo ObjectId.
 */
@Document(collection = "users")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserAccount {

    @Id
    private String id;

    @Indexed(unique = true)
    private String email;

    private String passwordHash;

    private String fullName;

    private String phoneNumber;

    private Role role;

    private AccountStatus status;

    private Instant createdAt;

    private Instant updatedAt;
}
